version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: soketi-dashboard
        restart: always
        ports:
            - "8000:8000"  # expose to host for Nginx to reverse proxy
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
