version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: soketi-admin
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/soketi-admin
            - ./storage:/var/www/soketi-admin/storage
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
